/*
 * RE-AGENT-BANNER
 * Windows API Stub Header for SOTE Disc-less Operation
 * Generated by Coordinator Agent for MinGW Cross-compilation
 * Artifact: SOTE.original.exe (SHA256: be596ee755afbd4f3a50de366a07866d8dfed032f3341b63f539e5f93773ff77)
 * Build Tag: rebuild-m100
 * Disc-less Mode: ENABLED
 */

#ifndef WINDOWS_API_STUBS_H
#define WINDOWS_API_STUBS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Windows API Stub implementations are provided in windows_api_stubs.c
// Function declarations are in sote.h to avoid conflicts
// This header exists primarily for documentation purposes

#ifdef __cplusplus
}
#endif

#endif /* WINDOWS_API_STUBS_H */

/*
 * RE-AGENT-TRAILER-JSON
 * {
 *   "header": "windows_api_stubs.h",
 *   "purpose": "Windows API stub declarations for disc-less cross-compilation",
 *   "symbols": ["load_config", "initialize_directdraw", "shutdown_directdraw", "get_game_time", "update_game_timer"],
 *   "artifact_sha256": "be596ee755afbd4f3a50de366a07866d8dfed032f3341b63f539e5f93773ff77"
 * }
 */