/*
 * RE-AGENT-BANNER
 * Windows API Stub Implementations for SOTE Disc-less Operation
 * Generated by Coordinator Agent for MinGW Cross-compilation
 * Artifact: SOTE.original.exe (SHA256: be596ee755afbd4f3a50de366a07866d8dfed032f3341b63f539e5f93773ff77)
 * Build Tag: rebuild-m100
 * Disc-less Mode: ENABLED
 */

#include "../include/sote.h"
#include "../include/windows_api_stubs.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

// Game time tracking for disc-less operation
static uint32_t game_start_time = 0;
static uint32_t last_game_time = 0;

/*
 * load_config - Load game configuration (disc-less implementation)
 * In disc-less mode, we use default configuration values
 */
BOOL load_config(ConfigData* config)
{
    #ifdef SOTE_DISCLESS
    printf("[DISCLESS] Loading default configuration\n");
    // Initialize config with default values
    if (config) {
        // Set default disc-less configuration
        memset(config, 0, sizeof(ConfigData));
    }
    return 1; // TRUE - Success
    #else
    // Original implementation would load from CD
    return 0; // FALSE - Error
    #endif
}

/*
 * initialize_directdraw - Initialize DirectDraw subsystem
 * Stub implementation for cross-platform compatibility
 */
HRESULT initialize_directdraw(GraphicsContext* ctx)
{
    #ifdef WIN32
    printf("[STUB] DirectDraw initialization (Windows)\n");
    #else
    printf("[STUB] DirectDraw initialization (Linux/Wine)\n");
    #endif
    
    if (ctx) {
        // Initialize graphics context with minimal setup
        memset(ctx, 0, sizeof(GraphicsContext));
    }
    
    return 0; // S_OK - Success
}

/*
 * shutdown_directdraw - Shutdown DirectDraw subsystem
 * Stub implementation for cross-platform compatibility
 */
void shutdown_directdraw(GraphicsContext* ctx)
{
    #ifdef WIN32
    printf("[STUB] DirectDraw shutdown (Windows)\n");
    #else
    printf("[STUB] DirectDraw shutdown (Linux/Wine)\n");
    #endif
    
    if (ctx) {
        // Clean up graphics context
        memset(ctx, 0, sizeof(GraphicsContext));
    }
}

/*
 * get_game_time - Get current game time in milliseconds
 * Uses system time as fallback in disc-less mode
 */
DWORD get_game_time(void)
{
    if (game_start_time == 0) {
        game_start_time = (uint32_t)time(NULL);
    }
    
    uint32_t current_time = (uint32_t)time(NULL);
    last_game_time = (current_time - game_start_time) * 1000; // Convert to milliseconds
    
    return (DWORD)last_game_time;
}

/*
 * update_game_timer - Update internal game timer
 * Stub implementation for disc-less operation
 */
void update_game_timer(GameState* state)
{
    // Update internal timer state
    get_game_time();
    
    #ifdef SOTE_DISCLESS
    // In disc-less mode, we don't need CD-ROM timing synchronization
    #endif
    
    if (state) {
        // Update game state timer if available
        // Note: Actual GameState structure layout would be needed for full implementation
    }
}

/*
 * RE-AGENT-TRAILER-JSON
 * {
 *   "implementation": "windows_api_stubs",
 *   "symbols": ["load_config", "initialize_directdraw", "shutdown_directdraw", "get_game_time", "update_game_timer"],
 *   "disc_less": true,
 *   "cross_platform": true,
 *   "artifact_sha256": "be596ee755afbd4f3a50de366a07866d8dfed032f3341b63f539e5f93773ff77"
 * }
 */